### PR TITLE
Create a page where people can sign that they hate reddit

### PR DESCRIPTION
**Pull request by WaveLinkdev**
Yes it uses an exposed google sheets API, cope and seethe

### CODE REVIEW

**Comment by WaveLinkdev** [comment]
immapush this if no comments

**Comment by heladeradr** [comment]
bro wtf

**Comment by heladeradr** [comment]
you removed @iQuickDev 's chatroom button

**Comment by heladeradr** [comment]
💀

**Comment by WaveLinkdev** [comment]
No, i didnt change that at all, its a completely separate site

**Comment by WaveLinkdev** [comment]
Its in /reddit-sucks/index.html, not the base index.html

**Comment by iQuickDev** [comment]
all i can say is that this is broken af

**Comment by WaveLinkdev** [comment]
It is very much broken, thats the fun of it tho I guess. Not going to make an entire API, its 1 am here

**Pull request merged**
