### PR TITLE
new better harder website

### PR DESCRIPTION
**Pull request by heladeradr**

### CODE REVIEW

**Comment by patstha** [comment]
add screenshots please 

puede magsalita nang screenshots

**Comment by heladeradr** [comment]
no fuck you do it yourself

**Comment by WaveLinkdev** [comment]
fuck reddit yeaaah

**Comment by D-u-c-k-s-e-l** [comment]
Can you please put it in a folder like `/website/` so that it doesn't make a messy base directory?

**Comment by heladeradr** [comment]
bruh merge this already
image

**Pull request merged**
